chore[#1]: git identity global setting

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,15 +21,25 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan github.com >> ~/.ssh/known_hosts
 
-      - name: Install dependencies & Deploy
+      - name: Configure Git Identity
         run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+
+      - name: Clone or Pull Repository
+        run: |
+          set -e
 
           cd /data1/team12
-          if [ ! -d "ai-model" ]; then
-            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:NoSleep-Drive/ai-model.git
-          else
+
+          if [ -d "ai-model/.git" ]; then
+            echo "Repository exists -> pulling latest changes..."
             cd ai-model
             GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git pull origin main
+          else
+            echo "Repository not found or not a git repo -> cloning from scratch"
+            rm -rf ai-model 
+            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:NoSleep-Drive/ai-model.git
           fi
+
+          echo "Model Deployment Ready"
